/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useEffect } from "react";

export default function PrivacyPolicy({ onNavigate }: { onNavigate?: (view: string) => void }) {
  useEffect(() => { 
    window.scrollTo(0, 0); 
  }, []);

  return (
    <div className="w-full bg-white font-sans selection:bg-[#002D62] selection:text-white pb-0">
      
      {/* =========================================
          L&T STYLE CORPORATE HERO BANNER
      ========================================= */}
      <div className="relative w-full h-[300px] md:h-[350px] flex items-end pb-12 px-6 md:px-12 lg:px-24">
        <div className="absolute inset-0 z-0">
          {/* Corporate Office/Tech Background Image */}
          <img 
            src="https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80" 
            alt="Corporate Office" 
            className="w-full h-full object-cover grayscale-[30%]"
          />
          {/* Dark Overlay gradient for readable text */}
          <div className="absolute inset-0 bg-gradient-to-r from-[#001730]/95 via-[#001730]/70 to-[#001730]/30"></div>
        </div>
        
        <div className="relative z-10 max-w-[1200px] w-full mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold font-heading tracking-tight text-white mb-2">
            Global Privacy Policy
          </h1>
          <div className="w-16 h-1 bg-[#00A3E0]"></div>
        </div>
      </div>

      {/* =========================================
          L&T STYLE CLEAN DOCUMENT LAYOUT
      ========================================= */}
      <div className="max-w-[1200px] mx-auto px-6 md:px-12 lg:px-24 pt-16 relative">
        
        {/* Subtle background abstract graphic (Optional Corporate Touch) */}
        <div className="absolute top-10 right-10 opacity-5 pointer-events-none hidden md:block">
           <svg width="400" height="200" viewBox="0 0 400 200" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M0 100 C 100 0, 300 200, 400 100" stroke="#002D62" strokeWidth="2" strokeDasharray="5 5"/>
              <path d="M0 120 C 150 20, 250 220, 400 120" stroke="#00A3E0" strokeWidth="1"/>
           </svg>
        </div>

        <div className="text-slate-700 font-light leading-relaxed text-sm md:text-base space-y-10 max-w-4xl">
          
          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Introduction</h2>
            <p className="mb-4">
              This Global Privacy Policy outlines the framework within which Cestrix Group Limited and its subsidiaries ("Cestrix Group", "we", "our", or "us") collect, use, maintain, and disclose information collected from users of our enterprise platforms, corporate websites, and digital integration services.
            </p>
            <p>
              At Cestrix Group, we adhere to the highest international standards of data security, ensuring complete confidentiality for our infrastructure and technology partners. We are committed to protecting the privacy and security of your corporate data in compliance with applicable global data protection regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Scope of Information Collection</h2>
            <p className="mb-4">
              Cestrix Group strictly limits data collection to professional and enterprise metrics essential for B2B technological integration and EPC contracting. When you engage with our digital ecosystems, we may collect the following:
            </p>
            <ul className="list-disc pl-6 space-y-2 marker:text-[#002D62] mb-6">
              <li><strong>Corporate Identity Data:</strong> Names, job titles, corporate email addresses, and contact coordinates submitted through official inquiries.</li>
              <li><strong>Enterprise Metrics:</strong> Project scale parameters, architectural requirements, and technical architecture requisites necessary for commercial estimation.</li>
              <li><strong>Telemetry Data:</strong> Machine-level analytics generated by equipment integrated with our IoT and Digital Twin platforms.</li>
            </ul>
            <p className="font-semibold text-[#002D62] mb-2">
              Exclusion of Sensitive Personal Data:
            </p>
            <p>
              We explicitly do not collect, process, or store sensitive personal consumer data. Our digital infrastructure is built exclusively for sovereign and corporate entities.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Operational Data Utilization</h2>
            <p className="mb-4">
              Information submitted through our portals is deployed exclusively for enterprise facilitation. We utilize this data to:
            </p>
            <ul className="list-disc pl-6 space-y-2 marker:text-[#002D62]">
              <li>Engineer custom Enterprise Resource Planning (ERP) frameworks tailored to your industrial needs.</li>
              <li>Execute high-precision 5D BIM and digital twin simulations for mega-construction projects.</li>
              <li>Establish live IoT telematics and monitor active heavy engineering sites.</li>
              <li>Facilitate secure vendor evaluations, procurement processes, and contract administration.</li>
              <li>Respond to corporate inquiries and provide requested commercial estimations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Zero-Trust Security & Confidentiality</h2>
            <p className="mb-4">
              Acknowledging the critical nature of our clients' operations across aviation, marine, defense, and power sectors, Cestrix Group operates under a strict non-disclosure architecture.
            </p>
            <p>
              All digital communications are routed through air-gapped, zero-trust cloud environments. We employ AES-256 encryption and adhere strictly to global cybersecurity standards, including ISO/IEC 27001 frameworks. Your enterprise intelligence is never monetized, traded, or shared with third-party data brokers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Data Retention & Rights</h2>
            <p>
              We retain corporate data only for as long as necessary to fulfill the purposes outlined in this policy, or as required by statutory, regulatory, or legal obligations. Authorized representatives of our corporate clients hold the right to request access to, modification of, or deletion of their enterprise data records maintained by Cestrix Group.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#002D62] font-heading mb-4">Contacting the Data Protection Office</h2>
            <p className="mb-4">
              For any clarifications regarding this Privacy Policy, or to exercise your enterprise data rights, please contact our Data Protection Officer at:
            </p>
            {/* L&T style plain text contact block, NO form */}
            <div className="bg-[#F8FAFC] p-6 border-l-4 border-[#002D62] text-sm text-slate-800">
              <strong className="block mb-2 font-heading uppercase tracking-widest text-xs text-[#00A3E0]">Official Communication</strong>
              Email: <a href="mailto:privacy@cestrixgroup.com" className="text-[#002D62] font-semibold hover:underline">privacy@cestrixgroup.com</a> <br/>
              Corporate Headquarters: Cestrix Group Limited
            </div>
          </section>

        </div>

        <div className="mt-20 pt-8 pb-16 border-t border-slate-200 flex flex-col md:flex-row justify-between items-center text-xs text-slate-500 font-medium">
           <span>Document Ref: CTX-POL-2026-08 (Effective: August 2026)</span>
           <span className="mt-2 md:mt-0">© {new Date().getFullYear()} Cestrix Group Limited. All Rights Reserved.</span>
        </div>
      </div>
      
    </div>
  );
}